### PR TITLE
Update repo to current version

### PR DESCRIPTION
**Pull request by Quake-Engines**

### CODE REVIEW

**Comment by illwieckz** [comment]
Hi, do you know that if you use the _“rebase and merge”_ option from github, it prevents the creation of a merge commit? :wink:

**Comment by Quake-Engines** [comment]
Hello. I didn't know that specifically, but I understood that I didn't do it right. I was just experimenting and forgot to delete my failed attempt and make clean fork. I'm not an expert in git, and couldn't yet find the proper way to update my forks with recent updates from original repositories, at least without cloning it on local machine first.

**Comment by illwieckz** [comment]
You can switch the merge mode this way:

[GitHub rebase and merge](https://dl.illwieckz.net/b/github/screenshots/20200202-130316-000.github-rebase-and-merge.png)

**Comment by illwieckz** [comment]
To fix the repository and remove the merge commit I see no other way to force push it, unfortunately.

**Comment by illwieckz** [comment]
If you use that _“rebase and merge”_ operation, since your tree is just tracking upstream, you're garanteed to keep a perfect clone of upstream. This way there is no need for you to make a clean fork or to clone locally before pushing, you just have to make a PR from time to time and merge with a _“rebase and merge”_ operation.

**Comment by Quake-Engines** [comment]
Sorry, this topic of different branches, and github interface still confuses me. I don't understand how to make it look like on your screenshot. The problem is the same as what I experienced before - when I click "pull request" or "compare" button in my fork (in right bottom corner of screenshot):
2020-02-02 15_29_47-Window

Then I got this:
2020-02-02 15_22_31-Window

So I can merge changes from my fork to the original repo, not the other way around.

**Comment by QuakeEngines** [comment]
But just now seems like I found workaround - to first change some other branch from this list (like default user)
2020-02-02 15_23_06-Window

Then check Daemon engine from the right list
2020-02-02 15_23_57-Window

And then change it to my fork on the left list:
2020-02-02 15_24_26-Window

But I'm don't know what whould I do if there was no other branches.

**Comment by QuakeEngines** [comment]
Because if I don't use this intermediate step with some unrelated branch, and simply select my fork from left list (or the other way around - select Daemon engine from right list), I will see something like this:
2020-02-02 15_46_39-Window

With ability to only select branches of my fork

**Comment by Quake-Engines** [comment]
Oh, now I see there's a link above "compare across forks", which helped me switch branches, sorry about that.

So, I just tried to merge it like you said with rebase, seems like its fine now?

**Comment by Quake-Engines** [comment]
I will probably delete this fork and make it again, to get rid of this failed commit.

**Comment by Quake-Engines** [comment]
Thank you for your suggestion

**Comment by illwieckz** [comment]
if you can clone and force-push, you don't have to delete the fork :smiley:

**Comment by illwieckz** [comment]
Try this on your computer:

```sh
git clone git@github.com:DaemonEngine/Daemon.git
cd Daemon
git remote add myself git@github.com:QuakeEngines/Daemon.git
git push --force --set-upstream myself master
```

**Comment by Quake-Engines** [comment]
Thanks. I will try this, I just need to configure my git for multiple accounts first. I rely too much on gui.

**Comment by Quake-Engines** [comment]
Ok, I did it - "This branch is even with DaemonEngine:master." 
Thanks again for your help.

**Comment by illwieckz** [comment]
Hi, can you send me an email to `dev@<my nickname>.net`? =)

**Comment by Quake-Engines** [comment]
I wrote you

**Pull request merged**
